### ISSUE TITLE
Complete type definitions

### ISSUE THREAD

**Issue by parkerduckworth** [weaviate/typescript-client#1]
The [JavaScript client PR](https://github.com/weaviate/weaviate-javascript-client/pull/121) which migrated this client from untyped javascript included some types, but not all of them. Now there are a remainder of any types which should be assigned their proper types, where possible.

A quick way to determine where these changes need to be made can be done by grepping the repo for `: any`.

**Comment by dirkkul** [comment]
We have someone working on this issue from our comunity
