### ISSUE TITLE
UUID not available in datatypes for class config

### ISSUE THREAD

**Issue by michael-pont** [weaviate/typescript-client#120]
uuid and uuid[] not available in 3.0.0-beta.20
Will the available datatypes match those from the docs here: https://weaviate.io/developers/weaviate/config-refs/datatypes?
![image](https://github.com/weaviate/typescript-client/assets/35072335/d8c18089-60f1-4416-97bc-face5e70969c)

**Comment by tsmith023** [comment]
Hi Michael, thanks for raising this! I somehow completely missed this from the API 😅 I will add it now to the next beta release!

**Comment by michael-pont** [comment]
Thanks! Excited to check out the new ts-client!

**Comment by tsmith023** [comment]
Have released `v3.0.0-beta.21` with this fix!
