### ISSUE TITLE
Type definition of withProperties should be any, not any[]?

### ISSUE THREAD

**Issue by erikvullings** [weaviate/typescript-client#15]
I've been using the javascript `weaviate-client` and just switched to this one. The migration was painless, and I only needed to make minor changes. One of them, however, surprised me. According to the [JS documentation](https://weaviate.io/developers/weaviate/api/rest/objects#update-a-data-object), `withProperties` requires an object (called schema in the example code from the website shown at the bottom). However, the TS documentation states it is a `any[]`. I prefer if it would be using generics, but shouldn't it be just `any`? 

TypeScript type definition in `updater.d.ts`:

```ts
withProperties: (properties: any[]) => this;
```

JavaScript example from the website:

```js
const weaviate = require('weaviate-client');

const client = weaviate.client({
  scheme: 'http',
  host: 'localhost:8080',
});

var className = 'Author';
var id = '36ddd591-2dee-4e7e-a3cc-eb86d30a4303';

client.data
    .getterById()
    .withClassName(className)
    .withId(id)
    .do()
    .then(res => {
        // alter the schema
        const schema = res.schema;
        schema.name = 'J. Kantor';
        return client.data
            .updater()
            .withId(id)
            .withClassName(thingClassName)
            .withProperties(schema)
            .withConsistencyLevel(weaviate.replication.ConsistencyLevel.ALL)  // default QUORUM
            .do();
        })
    .then(res => {
        console.log(res)
    })
    .catch(err => {
        console.error(err)
    });
```

**Comment by parkerduckworth** [comment]
Hey @erikvullings thanks for raising this issue. I agree with you that properties should be changed to `any`. PR #28 addresses this change.

**Comment by parkerduckworth** [comment]
Generics will be a nice improvement. Feel free to open a PR :)

**Comment by parkerduckworth** [comment]
A type for properties has been introduced:
- https://github.com/weaviate/typescript-client/blob/main/src/openapi/types.ts#L8
- https://github.com/weaviate/typescript-client/blob/main/src/openapi/schema.ts#L410
