### ISSUE TITLE
Improper(?) 'request was without tenant' error with aggregate request

### ISSUE THREAD

**Issue by tifroz** [weaviate/typescript-client#152]
Using the js v3 client (v3.0.6) + weaviate cloud, I am getting a `ClientError: class MyClass has multi-tenancy enabled, but request was without tenant` when executing the code below

```
const collection = (await client()).collections.get('MyClass').withTenant('hardcodedTenantId')
const response = await collection.aggregate.overAll({})
```

**Comment by tsmith023** [comment]
Thanks for the bug report, I can confirm that this is a missing feature! I will push a fix and release `v3.0.7` now, cheers!
