### ISSUE TITLE
Type Error: Hybrid query properties not accepting weights

### ISSUE THREAD

**Issue by michael-pont** [weaviate/typescript-client#178]
SDK Version `"weaviate-client": "^3.1.3"`

https://weaviate.io/developers/weaviate/search/hybrid#set-weights-on-property-values
is showing that weights can be applied to the properties.
Typescript is only allowing the keys of the type.

![image](https://github.com/user-attachments/assets/06bead8c-6dab-455d-b1b2-47608ea36b70)

Perhaps expanding PrimitiveKeys (https://bitly.cx/8kkg8) as a solution and then parsing out the ^<NUMBER>, or should the weights be included in another option field?
```typescript
type IsPrimitiveField<T> = T extends string | number | boolean | symbol | null | undefined ? T : never;

export type PrimitiveKeys<Obj> = Obj extends undefined
  ? string
  : {
      [Key in keyof Obj]-?: undefined extends Obj[Key]
        ? IsPrimitiveField<Exclude<Obj[Key], undefined>> extends never
          ? never
          : Key
        : IsPrimitiveField<Obj[Key]> extends never
        ? never
        : Key;
    }[keyof Obj] &
  string;

type AppendIndex<Key extends string, N extends number> = `${Key}^${N}`;

type GenerateTemplateStrings<Obj> = PrimitiveKeys<Obj> extends infer Keys
  ? Keys extends string
    ? Keys |
      AppendIndex<Keys, 2> |
      AppendIndex<Keys, 3> |
      AppendIndex<Keys, 4> |
      AppendIndex<Keys, 5> |
      AppendIndex<Keys, 6> |
      AppendIndex<Keys, 7> |
      AppendIndex<Keys, 8> |
      AppendIndex<Keys, 9> |
      AppendIndex<Keys, 10>
    : never
  : never;

type Example = {
    title: string
    description: string
    url: string
}



const queryProperties: GenerateTemplateStrings<Example>[] = ['description^2', 'title', 'url^4']
```

**Comment by tsmith023** [comment]
Hi @michael-pont, I'll be honest; I didn't realise this was a feature of Weaviate!
Thanks for reporting that it's missing from the TS client!

I think your second idea is a good one and I'll look into adding support for it now 😁 
The first idea is a nifty use of the type system but I think it would be preferable to make this aspect explicit for clarity

The type of `queryProperties` is likely to become:
```typescript
queryProperties: (PrimitiveKeys<T> | QueryProperty<T>)[]
```
where:
```typescript
type QueryProperty<T> = { name: PrimitiveKeys<T>, weight: number }
```
so that BC and FC is maintained and the edge case of adding a weight doesn't obscure the main path!

**Comment by michael-pont** [comment]
Yes, the 2nd approach makes more sense and is definitely more explicit. Thanks for adding it!
