### ISSUE TITLE
Support where filters in classifications

### ISSUE THREAD

**Issue by etiennedi** [weaviate/typescript-client#18]
## Background

Weaviate allows a set three different where filters in classifications, but the client currently does not take any arguments.

## Goals

* [ ] `.withSourceWhere()` is added to the classification builder
* [ ] `.withTrainingSetWhere()` is added to the classification builder
* [ ] `.withTargetWhere()` is added to the classification builder

**Comment by dirkkul** [comment]
will not do this - classification is rarely used
