### ISSUE TITLE
Add Anthropic module to client

### ISSUE THREAD

**Issue by malgamves** [weaviate/typescript-client#185]
Hey,

The anthropic module isn't accessible in the new release's type system. Refer to the screenshot below.

<img width="1016" alt="Screenshot 2024-08-13 at 13 36 37" src="https://github.com/user-attachments/assets/edd61414-c21c-4013-a6a0-845c6a02ed3d">

**Comment by ffleandro** [comment]
Has this been release with `3.1.4`?
I think #197 might be related to this.
