### ISSUE TITLE
Skip vectorization not applying when creating collection

### ISSUE THREAD

**Issue by ruidpm** [weaviate/typescript-client#193]
When creating a collection:

```javascript
 await client.collections.create({
      name: "Data",
      properties: [
        {
          name: "timestampedData",
          dataType: dataType.TEXT,
          skipVectorization: true,
          vectorizePropertyName: false,
        },
      ],
    });
```
It doesn't seem to be correctly applied to the property:
```
{ name: 'timestampedData',
 dataType: 'text',
 description: undefined,
 indexFilterable: true, 
indexInverted: false, 
indexRangeFilters: false,
 indexSearchable: true,
 vectorizerConfig: { 'text2vec-openai': { skip: false, vectorizePropertyName: false } },
 nestedProperties: undefined, 
tokenization: 'word' }
```
Version 3.1.4

**Comment by ruidpm** [comment]
Hi @tsmith023, thanks for looking into this. You are correct, I have it set up as as an environment variable, and adding the vectorizer to the client side configuration fixed it. Is this somewhere in the documentation that I missed?

Thanks

**Comment by tsmith023** [comment]
No, I think it likely that this is an undocumented effect that your usage highlights well!

If you would like it to be better documented, I encourage you to open an issue on the website repo: https://github.com/weaviate/weaviate-io, referencing this issue and someone can pick it up there. Cheers!
