### ISSUE TITLE
Failed to create collection with vectorizers using demo code in nodejs

### ISSUE THREAD

**Issue by Sandon** [weaviate/typescript-client#199]
Environment: free cloud sandbox instance on Weaviate Cloud (WCD)
Code language: nodejs (v18.20.4)
Version: weaviate-client (v3.1.5)
Code:
```
const client = await weaviate.connectToWeaviateCloud(
  clusterUrl,
  {
    authCredentials: new weaviate.ApiKey(apiKeyAdmin),
    headers: {
      'X-OpenAI-Api-Key': openaiApiKey
    }
  }
)

await client.collections.create({
    name: testCollectionName,
    vectorizers: [
      weaviate.configure.vectorizer.text2VecOpenAI({
        name: 'question_vector',
        sourceProperties: ['question'],
        model: 'text-embedding-3-large',
        dimensions: 1024
      })
    ],
    properties: [
      { name: 'category', dataType: dataType.TEXT },
      { name: 'question', dataType: dataType.TEXT },
      { name: 'answer', dataType: dataType.TEXT },
    ]
})
```

It’s demo code from the document. But it can not create collection with vectorizer. (The result is : collection is created, but the Vectorizer is empty when view in console page)

Plus: The openaiApiKey provided is corrent.

I don’t know what’s wrong. Need help here. Thanks.

**Comment by tsmith023** [comment]
Hi @Sandon!

Can you confirm that the collection was created as you expected in the server itself by doing:
```typescript
collection = client.collections.get(testCollectionName)
config = await collection.config.get()
console.log(JSON.stringify(config.vectorizers, null, 2)
```
and providing the result of the `console.log` command?

Currently, named vectors are not supported in the collections app on the Weaviate Cloud Console but this feature is in active development. If your collection was created successfully then you should see `config.vectorizers` populated in the console log. Cheers!

**Comment by Sandon** [comment]
> Hi @Sandon!
> 
> Can you confirm that the collection was created as you expected in the server itself by doing:
> 
> ```ts
> collection = client.collections.get(testCollectionName)
> config = await collection.config.get()
> console.log(JSON.stringify(config.vectorizers, null, 2)
> ```
> 
> and providing the result of the `console.log` command?
> 
> Currently, named vectors are not supported in the collections app on the Weaviate Cloud Console but this feature is in active development. If your collection was created successfully then you should see `config.vectorizers` populated in the console log. Cheers!

Using your code to console and get: 
```
{
  "default": {
    "vectorizer": {
      "name": "none"
    },
    "indexConfig": {
      "cleanupIntervalSeconds": 300,
      "distance": "cosine",
      "dynamicEfMin": 100,
      "dynamicEfMax": 500,
      "dynamicEfFactor": 8,
      "ef": -1,
      "efConstruction": 128,
      "flatSearchCutoff": 40000,
      "maxConnections": 32,
      "skip": false,
      "vectorCacheMaxObjects": 1000000000000,
      "type": "hnsw"
    },
    "indexType": "hnsw"
  }
}
```

**Comment by malgamves** [comment]
Hey @Sandon thanks for sharing these.

What version of Weaviate are you running your sandbox cluster on?
Could you try two things for me? 

1. Could you create a new collection using another vectorizer? e.g. cohere?
2. Could you try and create a collection by connecting to a local instance of Weaviate (setup is shown [here](https://weaviate.io/developers/weaviate/installation/docker-compose))

**Comment by Sandon** [comment]
It turns out to be a bug in my code. Thanks for your time.
