### ISSUE TITLE
Add tags to the GitHub repo for discoverability

### ISSUE THREAD

**Issue by dandv** [weaviate/typescript-client#23]
The JS repo has some tags, while this does not yet.

![image](https://user-images.githubusercontent.com/33569/228062688-2d11943f-e1eb-4cab-844d-59cd76ab7233.png)

Probably best to reuse some from [the core repo](https://github.com/weaviate/weaviate).

**Comment by tsmith023** [comment]
![Screenshot 2023-08-18 at 15 20 10](https://github.com/weaviate/typescript-client/assets/66489849/6eba45c3-385b-406e-8dd6-5c52ff14c3b3)
