### ISSUE TITLE
Redundant port specification with embedded DB

### ISSUE THREAD

**Issue by dandv** [weaviate/typescript-client#25]
In the [embedded example](https://github.com/weaviate/typescript-client/blob/main/examples/embedded/index.ts#L7-L9), the port needs to be specified twice. Could this be simplified?

The [Python client disallows](https://github.com/weaviate/weaviate-python-client/blob/3cf8a00d6ab13cb3d3e0487239f5fc9fe31f733a/weaviate/client.py#L136) specifying both the URL and embedded_options.

**Comment by parkerduckworth** [comment]
The port is specified because it is possible to have multiple embedded instances running per host. It can be omitted, and a default port of `6666` will be used.

Setting the host for the `EmbeddedOptions` will be disallowed however, because the embedded db will run on the same host as the client.
