### ISSUE TITLE
Typescript HeaderInit not defined

### ISSUE THREAD

**Issue by page-support** [weaviate/typescript-client#37]
I'm getting a type error in my weaviate client constructor saying that string is not the right type:

Type '{ 'X-OpenAI-Api-Key': string | undefined; }' is not assignable to type 'HeadersInit | undefined'.

"headers?: HeadersInit;" appears in index.ts in this repo but is not defined elsewhere in the repo.

**Comment by evenfrost** [comment]
What was the solution? I'm facing the TypeScript error every time I define `headers` and have to to `as unknown as Headers`.
