### ISSUE TITLE
Integrate the library with a Fastify Project

### ISSUE THREAD

**Issue by DylasX** [weaviate/typescript-client#39]
Hey I'm trying to integrate the typescript-client with a project made with Fastify

![image](https://user-images.githubusercontent.com/19805524/231313737-9a81b8e1-9954-4d4f-8937-53891eeee827.png)

I'm creating a plugin but the weaviate variable is always undefined I know this is something related with typescript so I share my tsconfig.json 

`{
  "extends": "fastify-tsconfig",
  "compilerOptions": {
    "strict": true,
    "sourceMap": false,
    "skipLibCheck": true,
    "target": "esnext",
    "module": "CommonJS",
    "outDir": "./dist",
    "typeRoots": ["@types"]
  },
  "include": ["src/**/*.ts"]
}
`

Thanks for the help!

**Comment by DylasX** [comment]
FYI: I already tried changing  "module"  to "esnext" but if I do that I will face a lot of errors coming from fastify

**Comment by ACGuillermo** [comment]
Facing the same problem in a NestJS project, it always returns undefined

**Comment by ACGuillermo** [comment]
I made it work using require instead of import.

// @ts-ignore
const weaviate = require('weaviate-ts-client');

**Comment by DylasX** [comment]
now working with "esModuleInterop" thanks!
