### ISSUE TITLE
How do I query object data using typescript client library with offset parameter?

### ISSUE THREAD

**Issue by Chuck1sn** [weaviate/typescript-client#47]
env:
weaviate-ts-client:1.1.0

https://weaviate.io/developers/weaviate/api/rest/objects#paging-offset

According to the documentation, the Query Object interface supports paginated queries, but I can't find the relevant API

```typescript
client.data
		.getter()
		.withOffset() // can not find offset api such like this
		.withClassName(schema)
		.withLimit(limit)
		.do()
		.then((res) => {
			console.log(res)
		})
		.catch((err) => {
			console.error(err)
		})
```

**Comment by MattFelice** [comment]
Have you tried using the graphql get way?

```javascript
client.graphql.get()
        .withClassName(className)
        .withLimit(1)
        .withOffset(10)
        .do();
```

**Comment by dirkkul** [comment]
check out this page of the docunmentation: https://weaviate.io/developers/weaviate/api/graphql/filters#cursor-with-after

The code examples are still missing (will add shortly) but you should be able to use `.withAfter(ID)`
