### ISSUE TITLE
Can't work with Edge Runtime

### ISSUE THREAD

**Issue by cm-igarashi-ryosuke** [weaviate/typescript-client#54]
When I try to use the `typescript-client` with the **Edge Runtime** API in Next.js, I get the error `XMLHttpRequest is not defined`.

The reason is that the default fetch for `graphql-request` is `cross-fetch`, and `cross-fetch` is not supported by Edge Runtime. (https://github.com/lquixada/cross-fetch/issues/142)

I have forked this repository and verified that it works with Edge Runtime by modifying the following. (My environment is Node.js 18)

https://github.com/cm-igarashi-ryosuke/typescript-client/pull/1/files

However, I am not familiar with the need for cross-fetch and there may be side effects.

I created this issue because I think some people may have trouble with the same event in the future.

Please let me know if you have a good solution.

**Comment by koolkao** [comment]
Similar issue here
