### ISSUE TITLE
'properties' does not exist in type 'HybridArgs'

### ISSUE THREAD

**Issue by dandv** [weaviate/typescript-client#57]
I see that [`properties` is included in `HybridArgs`](https://github.com/weaviate/typescript-client/blob/main/src/graphql/hybrid.ts) in 1.3.0, but the following code snippet fails with

> Argument of type '{ query: string; alpha: number; properties: string[]; }' is not assignable to parameter of type 'HybridArgs'.
  Object literal may only specify known properties, and 'properties' does not exist in type 'HybridArgs'.

```ts
import weaviate, { WeaviateClient } from 'weaviate-ts-client';

const client: WeaviateClient = weaviate.client({
  scheme: 'https',
  host: '...',
});

const response = await client.graphql
  .get()
  .withClassName('JeopardyQuestion')
  .withFields('question answer _additional{ score }')
  .withHybrid({
    query: 'Venus',
    properties: ["question"],  // <--
  })
  .do();
```

**Comment by parkerduckworth** [comment]
Hey @dandv, the support for this feature existed on master, but hadn't made it into a release yet.

I just made a release which contains hybrid class property support:
https://github.com/weaviate/typescript-client/releases/tag/v1.3.1
