### ISSUE TITLE
Unable to batch DELETE objects by id

### ISSUE THREAD

**Issue by hymloth** [weaviate/typescript-client#95]
Hi there, I am trying to batch DELETE objects by id, but it fails on 1.5.0

`

    await this.client.batch
        .objectsBatchDeleter()
        .withClassName('whatever')
        .withWhere({
          path: ['id'],
          operator: 'ContainsAny',
          valueTextArray:[x,y,z],
        })
        .do()
`
        
 The error I am getting is: usage error (422): {"code":606,"message":"match.match.where.operator in body should be one of [And Or Equal Like Not NotEqual GreaterThan GreaterThanEqual LessThan LessThanEqual WithinGeoRange IsNull]"}

**Comment by tsmith023** [comment]
This looks like a server error (due to the `422` report)!

Can you confirm whether you're using Weaviate `1.21.x`? `ContainsAny/All` were introduced in that release 😁

**Comment by hymloth** [comment]
Hi @tsmith023, yes, that was the issue. Updated to 1.21.3 and works like a charm!
